/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Reads nothing, needs no database. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a squad from a public FPL manager id.
         * @description Fetches the manager's last-locked picks from the public API and persists them. No credential is involved and none is accepted (D-013): the manager id is an input, not an identity. The pre-deadline unsaved squad is not public and is not returned. This is the one endpoint that calls upstream while you wait, so it carries a short timeout; a second call for the same manager and gameweek is served from GET /api/squad/{managerId}.
         */
        post: operations["SquadController_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether a set of players is a legal squad.
         * @description Returns EVERY broken rule, not just the first — a builder that reports one violation at a time makes the user play twenty questions with the form. Prices, positions and clubs are read from our own store, so the numbers cannot be supplied by the caller, and every limit comes from scoring_config rather than a constant.
         */
        post: operations["SquadController_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The optimizer's own best legal 15, in the same shape as an imported squad.
         * @description Solved fresh, and deliberately not persisted to squads — it belongs to no manager, and every solve is already recorded in optimizer_runs.
         */
        get: operations["SquadController_recommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A previously imported squad, from our own store.
         * @description Reads Postgres. Makes no upstream call.
         */
        get: operations["SquadController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advice for a squad built by hand.
         * @description The squad is validated first and refused if illegal: a captain and a bench for a team that cannot be fielded would read as encouragement.
         */
        post: operations["InsightsController_adviceForBuilt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advice for the optimizer's own squad.
         * @description Mostly useful as a check on the comparison: a squad measured against itself must report a gap of zero.
         */
        get: operations["InsightsController_adviceForRecommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advice for a previously imported squad.
         * @description Captain, vice, bench order and the gap against the best legal 15, with the model's per-term reasoning on every player, and `reasoning` for what the optimizer refused. Transfers and chips are a separate call: GET /insights/transfers/{managerId}.
         */
        get: operations["InsightsController_adviceForManager"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/transfers/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What to do with the squad this manager already has.
         * @description Transfers with the −4 hit inside the objective, priced at reconstructed SELL values rather than market prices, plus chip WINDOWS — a chip is unspendable once used, so the model names the gameweek the calendar argues for and never commits one.
         */
        get: operations["InsightsController_transferPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * What to do with a squad built by hand.
         * @description The squad is validated first and refused if illegal. Sell values are today’s market prices (a hand-built fifteen was never bought, so that is exact by construction), the free-transfer count is the one stated, and the bank defaults to what the fifteen leaves of the budget. Chips are all unspent. The response shape is the manager route’s, with managerId null.
         */
        post: operations["InsightsController_transferPlanForBuilt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every player in the game, with our expected points where we have them.
         * @description Served whole rather than paged: the row count is bounded by the game itself, and a picker filters across all of it at once. Expected points are null, not zero, for a player the model has not projected.
         */
        get: operations["PlayersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One player, whole: projections over the horizon, fixtures, form and availability.
         * @description The payload behind the player sheet. Projections are the served model’s, one per horizon gameweek, each with that gameweek’s fixtures and difficulty from the player’s side; `projections` is empty, not zeros, for a player the model has not reached.
         */
        get: operations["PlayersController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gameweeks/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The gameweek a decision can still be made for, with its deadline and the horizon.
         * @description Calendar only, no model output — so no `dataAsOfGw`. The first gameweek whose deadline has not passed, and the gameweek ids the advice is solved over from there.
         */
        get: operations["GameweeksController_next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseMetaDto: {
            /** @description Echoed from x-request-id, or generated per request. */
            requestId: string;
            /** @description Server-side handling time in milliseconds. */
            durationMs: number;
            /** Format: date-time */
            generatedAt: string;
            /** @description Which gameweek's data produced this. Present on every response carrying model output. */
            dataAsOfGw?: number;
        };
        ApiEnvelopeDto: {
            success: boolean;
            statusCode: number;
            message: string;
            /** @description Stable machine-readable key on failure, e.g. MANAGER_NOT_FOUND. Null when success is true. */
            errorCode: string | null;
            meta: components["schemas"]["ApiResponseMetaDto"] | null;
        };
        HealthDto: {
            /** @enum {string} */
            status: "ok";
            /** @example fpl-backend */
            service: string;
            /** @description Whole seconds since this process started. */
            uptimeSeconds: number;
        };
        SquadPickDto: {
            /** @description Our internal player id (cuid), not the FPL element id. */
            playerId: string;
            /** @description The player's FPL element id. */
            fplId: number;
            /** @example Haaland */
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @example MCI */
            teamShortName: string;
            /** @description Market price in tenths of a million. 55 is £5.5m. */
            nowCost: number;
            /** @description What a sale would return, in tenths. NULL for an imported squad and that is correct: no public endpoint carries a purchase or selling price. Filled by the transfer planner (B-008). */
            sellValue: number | null;
            /** @description 1-11 starting XI, 12-15 bench in substitution order. Called `position` upstream, renamed here because a pick already has a position in the GKP/DEF/MID/FWD sense and one field cannot be both. */
            slot: number;
            /** @description 1 normally, 2 for the captain, 3 under the triple-captain chip. */
            multiplier: number;
            isCaptain: boolean;
            isViceCaptain: boolean;
        };
        SquadDto: {
            /** @description The FPL manager id this squad was imported from. NULL for the recommended squad, which belongs to nobody. */
            managerId: number | null;
            /** @description The manager's display name, when the squad came from an import. */
            managerName: string | null;
            /** @description The gameweek this squad is the picks for. */
            gameweekId: number;
            /** @description Money not spent, in tenths of a million. */
            bank: number;
            /** @description Squad value excluding the bank, in tenths of a million. */
            teamValue: number;
            /** @description The chip active in this gameweek, e.g. bboost or 3xc. Null when none. */
            activeChip: string | null;
            /**
             * @description Which of the three ways this squad arrived (D-013). The advice is identical for all of them — that is the point of one shape.
             * @enum {string}
             */
            source: "import" | "recommended" | "built";
            picks: components["schemas"]["SquadPickDto"][];
        };
        ImportSquadDto: {
            /**
             * @description A public FPL manager id — the number in a manager's /entry/<id>/ URL on the official site.
             * @example 1
             */
            managerId: number;
        };
        ViolationDto: {
            /** @enum {string} */
            code: "SQUAD_SIZE" | "POSITION_QUOTA" | "BUDGET_EXCEEDED" | "CLUB_LIMIT" | "DUPLICATE_PLAYER" | "NO_LEGAL_FORMATION";
            /** @description Written for a person, not a log. */
            message: string;
        };
        SquadValidationDto: {
            legal: boolean;
            /** @description EVERY broken rule, not just the first. A builder that reports one violation at a time makes the user play twenty questions with the form. */
            violations: components["schemas"]["ViolationDto"][];
            /** @description Total cost in tenths of a million. */
            totalCost: number;
            /** @description Budget minus cost, in tenths. Negative means over budget. */
            bank: number;
            /** @description How many of each position, against the quota. */
            positionCounts: {
                [key: string]: number;
            };
            /** @description How many from each club, against the 3-per-club limit. */
            clubCounts: {
                [key: string]: number;
            };
        };
        ValidateSquadDto: {
            /** @description Our internal player ids (cuid). Order does not matter here. */
            playerIds: string[];
        };
        EvidenceDto: {
            /** @description Per-term breakdown of the next gameweek's expected points: appearance, goals, assists, cs, conceded, defcon, saves, bonus. The model's own reasoning, not a rationalisation. */
            components: {
                [key: string]: number;
            };
            /** @description Expected minutes in the next gameweek. */
            expectedMinutes: number;
            /** @description P(the player features at all). The term that dominates every other one — a 9-point forward who might not start is worth less than a 4-point one who certainly will. */
            playProbability: number;
            /** @description Standard deviation of the points distribution (B-017). NULL for a projection written by a model version that composed none — read it as unknown, never as zero. A zero here is a claim of certainty. */
            sd: number | null;
            /** @description P(2 points or fewer — the appearance and nothing else). What a human means by a blank, and the number that separates two players with the same expected points. */
            pBlank: number | null;
            /** @description P(10 points or more). */
            pHaul: number | null;
        };
        HorizonFixtureDto: {
            /** @example MCI */
            opponentShortName: string;
            isHome: boolean;
            /** @description FPL’s difficulty of this fixture from THIS player’s side, 1–5. A home player reads the home figure; the inverted reading looks just as plausible on screen and is wrong. */
            difficulty: number;
        };
        HorizonGameweekDto: {
            gameweekId: number;
            /** @description The served model’s expected points for this gameweek. Null where it has no row — a null is not a zero, and a horizon cell must render it as absence. */
            expectedPoints: number | null;
            /** @description This gameweek’s fixtures for the player’s club. Empty for a blank. */
            fixtures: components["schemas"]["HorizonFixtureDto"][];
        };
        AdvicePlayerDto: {
            playerId: string;
            fplId: number;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description a=available d=doubtful i=injured s=suspended u=unavailable n=not in squad. Only "a" is safe to start. Carried here so a flag can sit on the shirt without a second fetch (plan 030). */
            status: string;
            /** @description The availability note, when there is one. */
            news: string | null;
            /** @description FPL’s own chance of playing next round, as a percentage. Null when FPL has published none. */
            chanceOfPlayingNextRound: number | null;
            /**
             * @description What this player should do, not what the manager currently has them doing.
             * @enum {string}
             */
            role: "captain" | "vice" | "starter" | "bench";
            /** @description 1-4 for a bench player, in substitution order; null for a starter. Order is a real decision: auto-subs walk the bench in this order and the first eligible player comes on. */
            benchOrder: number | null;
            /** @description Expected points for the next gameweek alone. */
            epNextGw: number;
            /** @description Expected points over the horizon, decayed — the number the optimizer actually maximises. */
            epHorizon: number;
            /** @description Null when the model has no projection for this player in the next gameweek. */
            evidence: components["schemas"]["EvidenceDto"] | null;
            /** @description One entry per horizon gameweek, in `horizonGameweekIds` order (plan 032): the projection and the fixtures behind it, so a pitch, a ledger and a plan can show the run without a fetch per player. Undecayed, unlike `epHorizon`. */
            horizon: components["schemas"]["HorizonGameweekDto"][];
        };
        SquadDifferenceDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Expected points over the horizon. */
            epHorizon: number;
        };
        ComparisonDto: {
            /** @description Horizon EP summed over this squad's 15. */
            squadHorizonEp: number;
            /** @description Horizon EP summed over the optimal 15. */
            optimalHorizonEp: number;
            /** @description optimalHorizonEp − squadHorizonEp. Never negative: the optimal squad is optimal, so a negative gap would mean the comparison is broken, and a test asserts it cannot happen. */
            horizonGap: number;
            /** @description Next-gameweek EP of the best XI from this squad, captain counted twice — what the manager should actually score if the model is right. */
            xiNextGwEp: number;
            /** @description The same for the optimal squad. */
            optimalXiNextGwEp: number;
            /** @description optimalXiNextGwEp − xiNextGwEp. */
            xiNextGwGap: number;
            /** @description The formation the best XI from this squad plays. */
            formation: string;
            /** @description The optimal squad's formation. */
            optimalFormation: string;
            /** @description In the optimal 15 and not in this squad. **Not a transfer recommendation** — a transfer costs money and possibly 4 points, and deciding whether one is worth it is the transfer plan (GET /insights/transfers/{managerId}, or POST /insights/transfers for a built 15). This is the set difference and nothing more. */
            optimalHasThatYouDoNot: components["schemas"]["SquadDifferenceDto"][];
            /** @description In this squad and not in the optimal 15. Same caveat. */
            youHaveThatOptimalDoesNot: components["schemas"]["SquadDifferenceDto"][];
        };
        FloorExcludedPlayerDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @description e.g. "CHE". Never a team id — see the collision note below. */
            teamShortName: string;
            /** @description Premier League appearances, archive plus this season. Below the threshold, which is why this player was not eligible. */
            appearances: number;
            /** @description Horizon expected points the unguarded solve valued them at. */
            epHorizon: number;
        };
        AppearanceFloorDto: {
            /** @description Minimum appearances to enter the candidate pool. */
            threshold: number;
            /** @description How many of the league the floor removed. */
            excluded: number;
            /** @description Horizon EP the floor cost, measured against the same solve with the floor lifted and the collision penalty unchanged — so the number isolates the floor. Null when not computed. */
            costEp: number | null;
            /** @description The excluded players an unguarded solve would actually have picked. Not "everyone below the threshold" — that list is hundreds long and says nothing about this recommendation. */
            wouldHaveMadeTheSquad: components["schemas"]["FloorExcludedPlayerDto"][];
            /** @description What this guard IS, carried in the payload so a UI cannot restate it more confidently than the evidence allows. */
            statement: string;
        };
        DefencePairDto: {
            /** @description The club both play for — e.g. "BHA". Never a team id. */
            club: string;
            /** @description The two defensive players, by web name. */
            players: string[];
            /** @description Horizon points charged for starting this pair together. */
            lambda: number;
        };
        HeldDefencePairDto: {
            /** @description The club both play for — e.g. "BHA". */
            club: string;
            players: string[];
        };
        DefenceConcentrationDto: {
            /** @description Horizon points charged per pair of our defensive players who START for the same club. */
            lambda: number;
            /** @description Same-club defensive pairs the fifteen holds, started or not. A pair with one member benched is held and not charged — a user should still see it, because the money was spent. */
            pairsHeld: number;
            /** @description Horizon EP charged, which is for the started pairs only. */
            penaltyEp: number;
            started: components["schemas"]["DefencePairDto"][];
            benched: components["schemas"]["HeldDefencePairDto"][];
            /** @description What this guard is, and what it is NOT. The correlation behind it was measured over three archived seasons; the CHARGE is a policy choice, because nothing has measured that a narrower squad scores more. A UI must not present it as if something had. */
            statement: string;
        };
        ReasoningDto: {
            appearanceFloor: components["schemas"]["AppearanceFloorDto"];
            defenceConcentration: components["schemas"]["DefenceConcentrationDto"];
        };
        AdviceDto: {
            /** @description The manager this advice is for. Null for the recommended squad. */
            managerId: number | null;
            /** @description The gameweek the advice is for — the next one. */
            gameweekId: number;
            /** @description Every gameweek in the horizon the epHorizon numbers cover. */
            horizonGameweekIds: number[];
            /** @description Which projection model produced these numbers. */
            modelVersion: string;
            /** @description Who to captain: the highest-EP player in the best XI. Null for an empty squad. */
            captain: components["schemas"]["AdvicePlayerDto"] | null;
            /** @description The fallback. */
            viceCaptain: components["schemas"]["AdvicePlayerDto"] | null;
            /** @description All 15, each with the role the model would give it and its evidence. */
            players: components["schemas"]["AdvicePlayerDto"][];
            comparison: components["schemas"]["ComparisonDto"];
            /** @description Why the RECOMMENDED squad is what it is — which players the appearance floor removed and what that cost, and which fixture collisions the recommendation kept and what it paid. It describes the optimal squad, not the one being advised on, and is null only if the solve produced none. */
            reasoning: components["schemas"]["ReasoningDto"] | null;
            /** @description What this advice deliberately does not answer, in plain language, so the gap is visible in the payload rather than only in a plan file. */
            notAdvisedOn: string[];
        };
        AdviceRequestDto: {
            /** @description Our internal player ids (cuid) for the 15. */
            playerIds: string[];
        };
        TransferOutDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Horizon expected points, decayed. */
            epHorizon: number;
            /** @description What selling returns, in tenths: purchase price plus half the rise, rounded down. Null when the purchase price could not be reconstructed at all. */
            sellValue: number | null;
            /**
             * @description Where the purchase price came from. 'transfer-log' is exact — the manager's own element_in_cost. 'starting-gameweek-price' is exact for a player held since their first gameweek, because FPL's per-gameweek value IS the price that week. 'market-price' is exact by construction: a hand-built fifteen was never bought, so every player sells for what he costs today. 'unknown' means the budget used the market price for a player who WAS bought, which overstates it.
             * @enum {string}
             */
            sellValueSource: "transfer-log" | "starting-gameweek-price" | "market-price" | "unknown";
        };
        TransferSideDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Horizon expected points, decayed. */
            epHorizon: number;
        };
        PlannedMoveDto: {
            out: components["schemas"]["TransferOutDto"];
            in: components["schemas"]["TransferSideDto"];
            /** @description Horizon EP this single move adds, before any hit. The hit is charged once against the plan, not per move, because it is a property of how many moves there are. */
            gainEp: number;
        };
        ChipAdviceDto: {
            /** @enum {string} */
            chip: "bboost" | "3xc" | "freehit" | "wildcard" | "manager";
            label: string;
            /** @description The gameweek the CALENDAR argues for, or null when none in the horizon does — which is the common answer early in a season, not a failure. Never a gameweek for the wildcard: nothing in a fixture list argues for one. */
            gameweekId: number | null;
            /** @description Why, in the words a user would use. */
            reason: string;
            /** @description Already used, so there is nothing to advise. */
            spent: boolean;
        };
        TransferPlanDto: {
            /** @description Null for a plan from a hand-built fifteen (POST /insights/transfers). */
            managerId: number | null;
            /** @description The gameweek the plan is for — the next one. */
            gameweekId: number;
            horizonGameweekIds: number[];
            modelVersion: string;
            /** @description Free transfers in hand. For a manager, replayed from their own gameweek history — FPL exposes no free-transfer count publicly. For a hand-built fifteen, the number the user stated. */
            freeTransfers: number;
            /**
             * @description 'reconstructed' from the manager's gameweek history; 'stated' by the user for a hand-built fifteen, which nothing here can check.
             * @enum {string}
             */
            freeTransfersSource: "reconstructed" | "stated";
            /** @description False when the replay had a gap in it, which makes the count a lower bound rather than a number. Always true for a stated count: it is whatever the user said, not a bound. */
            freeTransfersReconstructed: boolean;
            /** @description Bank, in tenths of a million. */
            bank: number;
            /** @description Empty means hold — the solver always has holding available to it, so an empty plan is a decision and not a missing answer. */
            moves: components["schemas"]["PlannedMoveDto"][];
            /** @description Transfers beyond the free ones. */
            hits: number;
            /** @description Points those hits cost, as a positive number. */
            hitCost: number;
            /** @description Horizon EP of the squad as it stands. */
            currentEp: number;
            /** @description Horizon EP after the moves, with the hit already subtracted. */
            plannedEp: number;
            /** @description plannedEp − currentEp. Never negative: holding is always in the solver’s feasible set. */
            netGainEp: number;
            /** @description Picks whose sell value could not be reconstructed, so the budget used their market price. */
            sellValueUnknown: string[];
            chips: components["schemas"]["ChipAdviceDto"][];
            /** @description What this plan is not, in the payload rather than only in a plan file. */
            caveats: string[];
        };
        TransferPlanRequestDto: {
            /** @description Our internal player ids (cuid) for the 15. */
            playerIds: string[];
            /**
             * @description Free transfers in hand, as the user states them — nothing here can check the number. Capped at the bank FPL allows (5).
             * @default 1
             */
            freeTransfers: number;
            /** @description Bank in tenths of a million. Omitted, it is what the fifteen leaves of the budget at today's prices — what FPL would leave a manager who bought exactly this squad now. */
            bank?: number;
        };
        TeamFixtureDto: {
            gameweekId: number;
            /** @example MCI */
            opponentShortName: string;
            isHome: boolean;
            /** @description FPL’s difficulty from this club’s side, 1–5. A home club reads the home figure. */
            difficulty: number;
        };
        TeamFixturesDto: {
            /** @example MCI */
            teamShortName: string;
            /** @description The club’s fixtures over the horizon, in gameweek order. A blank gameweek has no row; a double has two. */
            fixtures: components["schemas"]["TeamFixtureDto"][];
        };
        PlayerListItemDto: {
            /** @description Our internal id (cuid) — what the squad endpoints take. */
            playerId: string;
            fplId: number;
            /** @example Haaland */
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @example MCI */
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description a=available d=doubtful i=injured s=suspended u=unavailable n=not in squad. Only "a" is safe to start. */
            status: string;
            /** @description The injury or availability note, when there is one. */
            news: string | null;
            /** @description Our expected points for the next gameweek. Null when the model has not projected this player — a null is not a zero, and the UI must not render it as one. */
            epNextGw: number | null;
            /** @description P(features at all) next gameweek. The term that dominates every other one. */
            playProbability: number | null;
            /** @description Our expected points summed over `horizonGameweekIds`, undecayed (plan 032). Null when the model has no row for this player in any of them. The number a builder sorts a run of fixtures by; the per-gameweek split is on `GET /api/players/{playerId}`. */
            epHorizon: number | null;
        };
        PlayerListDto: {
            /** @description Which gameweek the expected points are for. Null when nothing has been projected yet. */
            gameweekId: number | null;
            modelVersion: string | null;
            /** @description The gameweeks `epHorizon` is summed over and `fixtures` cover, in order. Empty before the calendar is synced. */
            horizonGameweekIds: number[];
            /** @description Every club’s horizon fixtures, once per club rather than once per player: a 651-row list joins on `teamShortName` instead of carrying 651 × 5 fixture rows (measured 129.5 KB raw before this field, 2026-09-03). */
            fixtures: components["schemas"]["TeamFixturesDto"][];
            /** @description Every player in the game. The list is bounded by the game itself — 612 in 2025/26 — so it is served whole rather than paged: a picker needs to filter across all of them at once. */
            count: number;
            players: components["schemas"]["PlayerListItemDto"][];
        };
        PlayerSeasonTotalsDto: {
            /** @description Matches with a recorded stat row this season. */
            appearances: number;
            points: number;
            minutes: number;
            goals: number;
            assists: number;
            cleanSheets: number;
            bonus: number;
            expectedGoals: number;
            expectedAssists: number;
        };
        PlayerFixtureDto: {
            /** @example MCI */
            opponentShortName: string;
            /** @description True when this player’s club is the home side. */
            isHome: boolean;
            /** @description FPL’s fixture difficulty rating for THIS player’s club in this match, 1 (easiest) to 5. Read from the side the player is on, so a home player sees the home difficulty. */
            difficulty: number;
            /** @description ISO instant. Null when FPL has not scheduled the match yet. */
            kickoffTime: string | null;
        };
        PlayerProjectionDto: {
            gameweekId: number;
            /** @description Expected points in this gameweek alone. */
            expectedPoints: number;
            /** @description Expected minutes in this gameweek. */
            expectedMinutes: number;
            /** @description P(the player features at all). */
            playProbability: number;
            /** @description Standard deviation of the points distribution. Null for a model version that composed none — unknown, never zero. */
            sd: number | null;
            /** @description P(2 points or fewer). Null when the model carried no distribution. */
            pBlank: number | null;
            /** @description P(10 points or more). Null when the model carried no distribution. */
            pHaul: number | null;
            /** @description Per-term breakdown of the expected points: appearance, goals, assists, cs, conceded, defcon, saves, bonus, fixtures. The model’s own reasoning, not a rationalisation. */
            components: {
                [key: string]: number;
            };
            /** @description The club’s fixtures in this gameweek. Empty is a blank, two is a double — both facts about the published calendar, not inferences. */
            fixtures: components["schemas"]["PlayerFixtureDto"][];
        };
        PlayerRecentGameweekDto: {
            gameweekId: number;
            /** @example ARS */
            opponentShortName: string;
            wasHome: boolean;
            minutes: number;
            /** @description FPL points actually scored in this match. */
            points: number;
            goals: number;
            assists: number;
            cleanSheets: number;
            bonus: number;
            /** @description Expected goals in this match, FPL’s own figure. */
            expectedGoals: number;
            /** @description Expected assists in this match, FPL’s own figure. */
            expectedAssists: number;
        };
        PlayerDetailDto: {
            /** @description Our internal id (cuid). */
            playerId: string;
            fplId: number;
            /** @example Haaland */
            webName: string;
            /** @example Erling Haaland */
            fullName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @example MCI */
            teamShortName: string;
            /** @example Man City */
            teamName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description a=available d=doubtful i=injured s=suspended u=unavailable n=not in squad. Only "a" is safe to start. */
            status: string;
            /** @description The availability note, when there is one. */
            news: string | null;
            /** @description FPL’s own chance of playing next round, as a percentage. Null when FPL has published none, which is the normal state for a fit player. */
            chanceOfPlayingNextRound: number | null;
            /** @description FPL’s form figure: points per match over the last 30 days. Null before any match. */
            form: number | null;
            /** @description FPL’s points per game this season. */
            pointsPerGame: number | null;
            /** @description Minutes played this season, FPL’s figure. */
            seasonMinutes: number;
            /** @description Starts this season, FPL’s figure. */
            seasonStarts: number;
            /** @description 1 means first-choice penalty taker. Null when not on the list. */
            penaltiesOrder: number | null;
            directFreekicksOrder: number | null;
            cornersOrder: number | null;
            /** @description Share of FPL managers who own this player, as a percentage, from the latest ownership snapshot. Null when none has been recorded. Ownership is a fact about the crowd, never an input to the projection. */
            selectedByPercent: number | null;
            /** @description Price change in tenths since this app first tracked the player — NOT since the season started, which no stored row can say. Null with fewer than two price points. */
            priceChangeSinceTracked: number | null;
            /** @description ISO instant of the first tracked price, so the change above can be dated. */
            priceTrackedSince: string | null;
            /** @description Summed from the per-gameweek stat rows. Null before the player has one. */
            seasonTotals: components["schemas"]["PlayerSeasonTotalsDto"] | null;
            /** @description The served model version the projections below came from. Null when nothing is projected. */
            modelVersion: string | null;
            /** @description The gameweeks a decision can still be made for, in order — the optimizer’s horizon. */
            horizonGameweekIds: number[];
            /** @description One entry per horizon gameweek the served model has projected, in gameweek order. Empty when the model has not reached this player. */
            projections: components["schemas"]["PlayerProjectionDto"][];
            /** @description The last finished matches, newest first. Empty before the season’s first match. */
            recent: components["schemas"]["PlayerRecentGameweekDto"][];
        };
        NextGameweekDto: {
            /** @description FPL’s event id, e.g. 3. */
            id: number;
            /** @example Gameweek 3 */
            name: string;
            /**
             * @description ISO 8601, UTC. The moment picks lock — the clock every screen counts down to.
             * @example 2026-09-04T17:30:00.000Z
             */
            deadlineTime: string;
            /** @description This gameweek and the ones after it that the advice is solved over, in order — the same read of the calendar the optimizer makes, so a horizon column on screen is the horizon in the numbers. */
            horizonGameweekIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["HealthDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    SquadController_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSquadDto"];
            };
        };
        responses: {
            /** @description The imported squad, now persisted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description No such manager id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "MANAGER_NOT_FOUND";
                    };
                };
            };
            /**
             * @description The squad contains a player this app has not synced.
             *
             *     The manager exists but has no readable picks yet — picks become public after a deadline.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_AVAILABLE_YET";
                    };
                };
            };
            /** @description The official API timed out or failed. Not the manager id's fault. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "FPL_UPSTREAM_UNAVAILABLE";
                    };
                };
            };
        };
    };
    SquadController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateSquadDto"];
            };
        };
        responses: {
            /** @description The verdict, with the counts behind it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadValidationDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description One of those player ids does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    SquadController_recommended: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recommended squad. managerId is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    SquadController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored squad. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description This manager has never been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    InsightsController_adviceForBuilt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdviceRequestDto"];
            };
        };
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description That squad breaks at least one rule — the message lists every one. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_ILLEGAL";
                    };
                };
            };
            /** @description One of those player ids does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    InsightsController_adviceForRecommended: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    InsightsController_adviceForManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description Import the squad first: POST /api/squad/import. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    InsightsController_transferPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["TransferPlanDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description Import the squad first: POST /api/squad/import. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    InsightsController_transferPlanForBuilt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferPlanRequestDto"];
            };
        };
        responses: {
            /** @description The plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["TransferPlanDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description That squad breaks at least one rule — the message lists every one. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_ILLEGAL";
                    };
                };
            };
            /** @description One of those player ids does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    PlayersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player universe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["PlayerListDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    PlayersController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Our internal id (cuid). */
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["PlayerDetailDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description No player with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    GameweeksController_next: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The next gameweek. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["NextGameweekDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description Every deadline has passed, or the calendar has not been synced. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "NO_UPCOMING_GAMEWEEK";
                    };
                };
            };
        };
    };
}
