/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Reads nothing, needs no database. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a squad from a public FPL manager id.
         * @description Fetches the manager's last-locked picks from the public API and persists them. No credential is involved and none is accepted (D-013): the manager id is an input, not an identity. The pre-deadline unsaved squad is not public and is not returned. This is the one endpoint that calls upstream while you wait, so it carries a short timeout; a second call for the same manager and gameweek is served from GET /api/squad/{managerId}.
         */
        post: operations["SquadController_import"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check whether a set of players is a legal squad.
         * @description Returns EVERY broken rule, not just the first — a builder that reports one violation at a time makes the user play twenty questions with the form. Prices, positions and clubs are read from our own store, so the numbers cannot be supplied by the caller, and every limit comes from scoring_config rather than a constant.
         */
        post: operations["SquadController_validate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The optimizer's own best legal 15, in the same shape as an imported squad.
         * @description Solved fresh, and deliberately not persisted to squads — it belongs to no manager, and every solve is already recorded in optimizer_runs.
         */
        get: operations["SquadController_recommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/squad/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A previously imported squad, from our own store.
         * @description Reads Postgres. Makes no upstream call.
         */
        get: operations["SquadController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advice for a squad built by hand.
         * @description The squad is validated first and refused if illegal: a captain and a bench for a team that cannot be fielded would read as encouragement.
         */
        post: operations["InsightsController_adviceForBuilt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advice for the optimizer's own squad.
         * @description Mostly useful as a check on the comparison: a squad measured against itself must report a gap of zero.
         */
        get: operations["InsightsController_adviceForRecommended"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/advice/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Advice for a previously imported squad.
         * @description Captain, vice, bench order and the gap against the best legal 15, with the model's per-term reasoning on every player, and `reasoning` for what the optimizer refused. Transfers and chips are a separate call: GET /insights/transfers/{managerId}.
         */
        get: operations["InsightsController_adviceForManager"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/transfers/{managerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What to do with the squad this manager already has.
         * @description Transfers with the −4 hit inside the objective, priced at reconstructed SELL values rather than market prices, plus chip WINDOWS — a chip is unspendable once used, so the model names the gameweek the calendar argues for and never commits one.
         */
        get: operations["InsightsController_transferPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every player in the game, with our expected points where we have them.
         * @description Served whole rather than paged: the row count is bounded by the game itself, and a picker filters across all of it at once. Expected points are null, not zero, for a player the model has not projected.
         */
        get: operations["PlayersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseMetaDto: {
            /** @description Echoed from x-request-id, or generated per request. */
            requestId: string;
            /** @description Server-side handling time in milliseconds. */
            durationMs: number;
            /** Format: date-time */
            generatedAt: string;
            /** @description Which gameweek's data produced this. Present on every response carrying model output. */
            dataAsOfGw?: number;
        };
        ApiEnvelopeDto: {
            success: boolean;
            statusCode: number;
            message: string;
            /** @description Stable machine-readable key on failure, e.g. MANAGER_NOT_FOUND. Null when success is true. */
            errorCode: string | null;
            meta: components["schemas"]["ApiResponseMetaDto"] | null;
        };
        HealthDto: {
            /** @enum {string} */
            status: "ok";
            /** @example fpl-backend */
            service: string;
            /** @description Whole seconds since this process started. */
            uptimeSeconds: number;
        };
        SquadPickDto: {
            /** @description Our internal player id (cuid), not the FPL element id. */
            playerId: string;
            /** @description The player's FPL element id. */
            fplId: number;
            /** @example Haaland */
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @example MCI */
            teamShortName: string;
            /** @description Market price in tenths of a million. 55 is £5.5m. */
            nowCost: number;
            /** @description What a sale would return, in tenths. NULL for an imported squad and that is correct: no public endpoint carries a purchase or selling price. Filled by the transfer planner (B-008). */
            sellValue: number | null;
            /** @description 1-11 starting XI, 12-15 bench in substitution order. Called `position` upstream, renamed here because a pick already has a position in the GKP/DEF/MID/FWD sense and one field cannot be both. */
            slot: number;
            /** @description 1 normally, 2 for the captain, 3 under the triple-captain chip. */
            multiplier: number;
            isCaptain: boolean;
            isViceCaptain: boolean;
        };
        SquadDto: {
            /** @description The FPL manager id this squad was imported from. NULL for the recommended squad, which belongs to nobody. */
            managerId: number | null;
            /** @description The manager's display name, when the squad came from an import. */
            managerName: string | null;
            /** @description The gameweek this squad is the picks for. */
            gameweekId: number;
            /** @description Money not spent, in tenths of a million. */
            bank: number;
            /** @description Squad value excluding the bank, in tenths of a million. */
            teamValue: number;
            /** @description The chip active in this gameweek, e.g. bboost or 3xc. Null when none. */
            activeChip: string | null;
            /**
             * @description Which of the three ways this squad arrived (D-013). The advice is identical for all of them — that is the point of one shape.
             * @enum {string}
             */
            source: "import" | "recommended" | "built";
            picks: components["schemas"]["SquadPickDto"][];
        };
        ImportSquadDto: {
            /**
             * @description A public FPL manager id — the number in a manager's /entry/<id>/ URL on the official site.
             * @example 1
             */
            managerId: number;
        };
        ViolationDto: {
            /** @enum {string} */
            code: "SQUAD_SIZE" | "POSITION_QUOTA" | "BUDGET_EXCEEDED" | "CLUB_LIMIT" | "DUPLICATE_PLAYER" | "NO_LEGAL_FORMATION";
            /** @description Written for a person, not a log. */
            message: string;
        };
        SquadValidationDto: {
            legal: boolean;
            /** @description EVERY broken rule, not just the first. A builder that reports one violation at a time makes the user play twenty questions with the form. */
            violations: components["schemas"]["ViolationDto"][];
            /** @description Total cost in tenths of a million. */
            totalCost: number;
            /** @description Budget minus cost, in tenths. Negative means over budget. */
            bank: number;
            /** @description How many of each position, against the quota. */
            positionCounts: {
                [key: string]: number;
            };
            /** @description How many from each club, against the 3-per-club limit. */
            clubCounts: {
                [key: string]: number;
            };
        };
        ValidateSquadDto: {
            /** @description Our internal player ids (cuid). Order does not matter here. */
            playerIds: string[];
        };
        EvidenceDto: {
            /** @description Per-term breakdown of the next gameweek's expected points: appearance, goals, assists, cs, conceded, defcon, saves, bonus. The model's own reasoning, not a rationalisation. */
            components: {
                [key: string]: number;
            };
            /** @description Expected minutes in the next gameweek. */
            expectedMinutes: number;
            /** @description P(the player features at all). The term that dominates every other one — a 9-point forward who might not start is worth less than a 4-point one who certainly will. */
            playProbability: number;
            /** @description Standard deviation of the points distribution (B-017). NULL for a projection written by a model version that composed none — read it as unknown, never as zero. A zero here is a claim of certainty. */
            sd: number | null;
            /** @description P(2 points or fewer — the appearance and nothing else). What a human means by a blank, and the number that separates two players with the same expected points. */
            pBlank: number | null;
            /** @description P(10 points or more). */
            pHaul: number | null;
        };
        AdvicePlayerDto: {
            playerId: string;
            fplId: number;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /**
             * @description What this player should do, not what the manager currently has them doing.
             * @enum {string}
             */
            role: "captain" | "vice" | "starter" | "bench";
            /** @description 1-4 for a bench player, in substitution order; null for a starter. Order is a real decision: auto-subs walk the bench in this order and the first eligible player comes on. */
            benchOrder: number | null;
            /** @description Expected points for the next gameweek alone. */
            epNextGw: number;
            /** @description Expected points over the horizon, decayed — the number the optimizer actually maximises. */
            epHorizon: number;
            /** @description Null when the model has no projection for this player in the next gameweek. */
            evidence: components["schemas"]["EvidenceDto"] | null;
        };
        SquadDifferenceDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Expected points over the horizon. */
            epHorizon: number;
        };
        ComparisonDto: {
            /** @description Horizon EP summed over this squad's 15. */
            squadHorizonEp: number;
            /** @description Horizon EP summed over the optimal 15. */
            optimalHorizonEp: number;
            /** @description optimalHorizonEp − squadHorizonEp. Never negative: the optimal squad is optimal, so a negative gap would mean the comparison is broken, and a test asserts it cannot happen. */
            horizonGap: number;
            /** @description Next-gameweek EP of the best XI from this squad, captain counted twice — what the manager should actually score if the model is right. */
            xiNextGwEp: number;
            /** @description The same for the optimal squad. */
            optimalXiNextGwEp: number;
            /** @description optimalXiNextGwEp − xiNextGwEp. */
            xiNextGwGap: number;
            /** @description The formation the best XI from this squad plays. */
            formation: string;
            /** @description The optimal squad's formation. */
            optimalFormation: string;
            /** @description In the optimal 15 and not in this squad. **Not a transfer recommendation** — a transfer costs money and possibly 4 points, and deciding whether one is worth it is B-008. This is the set difference and nothing more. */
            optimalHasThatYouDoNot: components["schemas"]["SquadDifferenceDto"][];
            /** @description In this squad and not in the optimal 15. Same caveat. */
            youHaveThatOptimalDoesNot: components["schemas"]["SquadDifferenceDto"][];
        };
        FloorExcludedPlayerDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @description e.g. "CHE". Never a team id — see the collision note below. */
            teamShortName: string;
            /** @description Premier League appearances, archive plus this season. Below the threshold, which is why this player was not eligible. */
            appearances: number;
            /** @description Horizon expected points the unguarded solve valued them at. */
            epHorizon: number;
        };
        AppearanceFloorDto: {
            /** @description Minimum appearances to enter the candidate pool. */
            threshold: number;
            /** @description How many of the league the floor removed. */
            excluded: number;
            /** @description Horizon EP the floor cost, measured against the same solve with the floor lifted and the collision penalty unchanged — so the number isolates the floor. Null when not computed. */
            costEp: number | null;
            /** @description The excluded players an unguarded solve would actually have picked. Not "everyone below the threshold" — that list is hundreds long and says nothing about this recommendation. */
            wouldHaveMadeTheSquad: components["schemas"]["FloorExcludedPlayerDto"][];
            /** @description What this guard IS, carried in the payload so a UI cannot restate it more confidently than the evidence allows. */
            statement: string;
        };
        CollisionTakenDto: {
            /** @description The match, home side first — e.g. "CHE vs BHA". Plan 009 specified this and what shipped emitted two team cuids, which is why nothing could render it: a cuid on screen looks like data. */
            fixture: string;
            attacker: string;
            defender: string;
            /** @description Horizon points charged for HOLDING this pair. Charged whether or not both sides start. */
            lambda: number;
            /** @description Whether the eleven started both sides of this pair. Holding is what is charged and starting is a separate fact (B-025): a squad can pay for a pair and field only one half of it, which is a state the payload had no way to express before — it reported no conflict at all. */
            bothStarted: boolean;
        };
        FixtureCollisionsDto: {
            /** @description Horizon points charged per conflicting pair the squad HOLDS. The policy constant itself: it was briefly scaled by the bench weight (B-025) and a second field carried the constant beside it, which B-026 undid — the scaling was exact only for a pair nobody starts. */
            lambda: number;
            /** @description Conflicting pairs across the whole candidate pool. */
            pairsConsidered: number;
            /** @description Horizon EP this SQUAD was charged for the pairs it holds. Before B-025 this was charged against the eleven, so a squad that owned both sides of a conflict and started one of them reported zero — a user told there was no conflict in a squad holding one. */
            penaltyEp: number;
            /** @description Every pair the squad holds, each with whether both sides started. Empty means the squad holds no conflicting pair — not that none was charged. */
            taken: components["schemas"]["CollisionTakenDto"][];
            /** @description What this guard is, and — unlike the floor — what it is NOT. It was measured over 103 archived gameweeks and did not improve realised points. A UI must not present it as if it had. */
            statement: string;
        };
        ReasoningDto: {
            appearanceFloor: components["schemas"]["AppearanceFloorDto"];
            fixtureCollisions: components["schemas"]["FixtureCollisionsDto"];
        };
        AdviceDto: {
            /** @description The manager this advice is for. Null for the recommended squad. */
            managerId: number | null;
            /** @description The gameweek the advice is for — the next one. */
            gameweekId: number;
            /** @description Every gameweek in the horizon the epHorizon numbers cover. */
            horizonGameweekIds: number[];
            /** @description Which projection model produced these numbers. */
            modelVersion: string;
            /** @description Who to captain: the highest-EP player in the best XI. Null for an empty squad. */
            captain: components["schemas"]["AdvicePlayerDto"] | null;
            /** @description The fallback. */
            viceCaptain: components["schemas"]["AdvicePlayerDto"] | null;
            /** @description All 15, each with the role the model would give it and its evidence. */
            players: components["schemas"]["AdvicePlayerDto"][];
            comparison: components["schemas"]["ComparisonDto"];
            /** @description Why the RECOMMENDED squad is what it is — which players the appearance floor removed and what that cost, and which fixture collisions the recommendation kept and what it paid. It describes the optimal squad, not the one being advised on, and is null only if the solve produced none. */
            reasoning: components["schemas"]["ReasoningDto"] | null;
            /** @description What this advice deliberately does not answer, in plain language, so the gap is visible in the payload rather than only in a plan file. */
            notAdvisedOn: string[];
        };
        AdviceRequestDto: {
            /** @description Our internal player ids (cuid) for the 15. */
            playerIds: string[];
        };
        TransferOutDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Horizon expected points, decayed. */
            epHorizon: number;
            /** @description What selling returns, in tenths: purchase price plus half the rise, rounded down. Null when the purchase price could not be reconstructed at all. */
            sellValue: number | null;
            /**
             * @description Where the purchase price came from. 'transfer-log' is exact — the manager's own element_in_cost. 'starting-gameweek-price' is exact for a player held since their first gameweek, because FPL's per-gameweek value IS the price that week. 'unknown' means the budget used the market price, which overstates it.
             * @enum {string}
             */
            sellValueSource: "transfer-log" | "starting-gameweek-price" | "unknown";
        };
        TransferSideDto: {
            playerId: string;
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description Horizon expected points, decayed. */
            epHorizon: number;
        };
        PlannedMoveDto: {
            out: components["schemas"]["TransferOutDto"];
            in: components["schemas"]["TransferSideDto"];
            /** @description Horizon EP this single move adds, before any hit. The hit is charged once against the plan, not per move, because it is a property of how many moves there are. */
            gainEp: number;
        };
        ChipAdviceDto: {
            /** @enum {string} */
            chip: "bboost" | "3xc" | "freehit" | "wildcard" | "manager";
            label: string;
            /** @description The gameweek the CALENDAR argues for, or null when none in the horizon does — which is the common answer early in a season, not a failure. Never a gameweek for the wildcard: nothing in a fixture list argues for one. */
            gameweekId: number | null;
            /** @description Why, in the words a user would use. */
            reason: string;
            /** @description Already used, so there is nothing to advise. */
            spent: boolean;
        };
        TransferPlanDto: {
            managerId: number;
            /** @description The gameweek the plan is for — the next one. */
            gameweekId: number;
            horizonGameweekIds: number[];
            modelVersion: string;
            /** @description Free transfers in hand, replayed from the manager's own gameweek history. FPL exposes no free-transfer count publicly. */
            freeTransfers: number;
            /** @description False when that replay had a gap in it, which makes the count a lower bound rather than a number. */
            freeTransfersReconstructed: boolean;
            /** @description Bank, in tenths of a million. */
            bank: number;
            /** @description Empty means hold — the solver always has holding available to it, so an empty plan is a decision and not a missing answer. */
            moves: components["schemas"]["PlannedMoveDto"][];
            /** @description Transfers beyond the free ones. */
            hits: number;
            /** @description Points those hits cost, as a positive number. */
            hitCost: number;
            /** @description Horizon EP of the squad as it stands. */
            currentEp: number;
            /** @description Horizon EP after the moves, with the hit already subtracted. */
            plannedEp: number;
            /** @description plannedEp − currentEp. Never negative: holding is always in the solver’s feasible set. */
            netGainEp: number;
            /** @description Picks whose sell value could not be reconstructed, so the budget used their market price. */
            sellValueUnknown: string[];
            chips: components["schemas"]["ChipAdviceDto"][];
            /** @description What this plan is not, in the payload rather than only in a plan file. */
            caveats: string[];
        };
        PlayerListItemDto: {
            /** @description Our internal id (cuid) — what the squad endpoints take. */
            playerId: string;
            fplId: number;
            /** @example Haaland */
            webName: string;
            /** @enum {string} */
            position: "GKP" | "DEF" | "MID" | "FWD";
            /** @example MCI */
            teamShortName: string;
            /** @description Market price in tenths of a million. */
            nowCost: number;
            /** @description a=available d=doubtful i=injured s=suspended u=unavailable n=not in squad. Only "a" is safe to start. */
            status: string;
            /** @description The injury or availability note, when there is one. */
            news: string | null;
            /** @description Our expected points for the next gameweek. Null when the model has not projected this player — a null is not a zero, and the UI must not render it as one. */
            epNextGw: number | null;
            /** @description P(features at all) next gameweek. The term that dominates every other one. */
            playProbability: number | null;
        };
        PlayerListDto: {
            /** @description Which gameweek the expected points are for. Null when nothing has been projected yet. */
            gameweekId: number | null;
            modelVersion: string | null;
            /** @description Every player in the game. The list is bounded by the game itself — 612 in 2025/26 — so it is served whole rather than paged: a picker needs to filter across all of them at once. */
            count: number;
            players: components["schemas"]["PlayerListItemDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["HealthDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    SquadController_import: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSquadDto"];
            };
        };
        responses: {
            /** @description The imported squad, now persisted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description No such manager id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "MANAGER_NOT_FOUND";
                    };
                };
            };
            /**
             * @description The squad contains a player this app has not synced.
             *
             *     The manager exists but has no readable picks yet — picks become public after a deadline.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_AVAILABLE_YET";
                    };
                };
            };
            /** @description The official API timed out or failed. Not the manager id's fault. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "FPL_UPSTREAM_UNAVAILABLE";
                    };
                };
            };
        };
    };
    SquadController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateSquadDto"];
            };
        };
        responses: {
            /** @description The verdict, with the counts behind it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadValidationDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description One of those player ids does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    SquadController_recommended: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recommended squad. managerId is null. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    SquadController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored squad. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["SquadDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description This manager has never been imported. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    InsightsController_adviceForBuilt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdviceRequestDto"];
            };
        };
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description That squad breaks at least one rule — the message lists every one. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_ILLEGAL";
                    };
                };
            };
            /** @description One of those player ids does not exist. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "UNKNOWN_PLAYER";
                    };
                };
            };
        };
    };
    InsightsController_adviceForRecommended: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
    InsightsController_adviceForManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The advice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["AdviceDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description Import the squad first: POST /api/squad/import. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    InsightsController_transferPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                managerId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["TransferPlanDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
            /** @description Import the squad first: POST /api/squad/import. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: null | null;
                        /** @enum {boolean} */
                        success?: false;
                        /** @enum {string} */
                        errorCode?: "SQUAD_NOT_IMPORTED";
                    };
                };
            };
        };
    };
    PlayersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player universe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelopeDto"] & {
                        data: components["schemas"]["PlayerListDto"];
                        /** @enum {boolean} */
                        success?: true;
                        /** @enum {string|null} */
                        errorCode?: null;
                    };
                };
            };
        };
    };
}
